wordcloud:
  enable: true
codeblock:
  copy_btn: true
creative_commons:
  license: by-nc-sa
  post: true
  language: deed.zh
  clipboard: false
banner:
  enable: true
  title: siroi
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line
post_meta:
  item_text: false
  created_at: true
  updated_at: false
  categories: true
  tags: true
footer:
  support:
    enable: true
    title: 又拍云
    link: https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: 本网站由
    suffix: 提供 CDN 加速